# Generated by Django 4.2.3 on 2023-08-09 10:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('location', models.TextField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('user', models.UUIDField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 10, 28, 423687, tzinfo=datetime.timezone.utc))),
                ('date_updated', models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 10, 28, 423701, tzinfo=datetime.timezone.utc))),
                ('number_of_submits', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
