# Generated by Django 4.2.3 on 2023-08-23 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_key_words_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 6, 47, 5, 9068, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 6, 47, 5, 9104, tzinfo=datetime.timezone.utc)),
        ),
    ]
