# Generated by Django 4.2.3 on 2023-08-23 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image_url_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_submited', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 7, 8, 34, 954982, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 7, 8, 34, 954002, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 7, 8, 34, 954016, tzinfo=datetime.timezone.utc)),
        ),
    ]
