# Generated by Django 4.2.3 on 2023-08-23 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_submit_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 8, 14, 46, 631652, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 8, 14, 46, 631675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='submit',
            name='date_submited',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 8, 14, 46, 632734, tzinfo=datetime.timezone.utc)),
        ),
    ]
