# Generated by Django 4.2.3 on 2023-08-23 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_date_posted_alter_post_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 50, 29, 647211, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 50, 29, 647224, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='submit',
            name='date_submited',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 50, 29, 647994, tzinfo=datetime.timezone.utc)),
        ),
    ]
