# Generated by Django 4.2.3 on 2023-08-08 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 12, 6, 52, 307590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 6, 52, 307635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 6, 52, 307621, tzinfo=datetime.timezone.utc)),
        ),
    ]
