# Generated by Django 4.2.3 on 2023-08-08 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_birthday_alter_user_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 12, 28, 57, 211992, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 28, 57, 212019, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 28, 57, 212011, tzinfo=datetime.timezone.utc)),
        ),
    ]
