# Generated by Django 4.2.3 on 2023-08-08 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_creation_date_alter_user_last_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 33, 20, 76263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 12, 33, 20, 76322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 33, 20, 76341, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 12, 33, 20, 76333, tzinfo=datetime.timezone.utc)),
        ),
    ]
