# Generated by Django 4.2.3 on 2023-08-09 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_creation_date_alter_user_last_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 10, 28, 407045, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 10, 28, 407073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 10, 10, 28, 407065, tzinfo=datetime.timezone.utc)),
        ),
    ]
