# Generated by Django 4.2.3 on 2023-08-23 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.UUIDField()),
                ('room', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=500)),
                ('time_sent', models.DateTimeField(default=datetime.datetime(2023, 8, 23, 10, 50, 29, 680553, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
